### ISSUE TITLE
Unhandled java.lang.RuntimeException

### ISSUE THREAD

**Issue by Tolriq** [ohmae/mmupnp#24]
Hi,

Just got this crash that seems to be an unhandled case when parsing description.

Would be cool if those where handled too.

And makes me ask again if there's a way to enhance the API to push back those errors + malformed description back to the application.
I have users complaining that their devices are not found probably because of malformed xml from the manufacturer but there's currently no way to get the information on client side.

It require either moving logging to an interface and allows consumers to implement that interface so we can log to our log files.
Or maybe better for improving the parser later and add hacks for problematic devices, expanding the DiscoveryListener interface to add something like onDiscoverError(Exception error, String description).

```
Fatal Exception: java.lang.RuntimeException: Undefined Prefix: ms in org.kxml2.io.KXmlParser@152b7f41
       at org.kxml2.io.KXmlParser.adjustNsp(KXmlParser.java:260)
       at org.kxml2.io.KXmlParser.parseStartTag(KXmlParser.java:1152)
       at org.kxml2.io.KXmlParser.next(KXmlParser.java:372)
       at org.kxml2.io.KXmlParser.nextToken(KXmlParser.java:317)
       at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:328)
       at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:295)
       at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:295)
       at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:295)
       at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:128)
       at net.mm2d.util.XmlUtils.newDocument(XmlUtils.java:79)
       at net.mm2d.upnp.ControlPoint$DeviceLoader.net.mm2d.upnp.DeviceParser.parseDescription(ControlPoint.java:3078)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

```

**Comment by ohmae** [comment]
Anyway, I add catch RuntimeExeption to avoided a crash and added log output.　https://github.com/ohmae/mmupnp/commit/cc4c1aa9e880efbf661eed931d882016a9c5b9a9

**Comment by Tolriq** [comment]
Thanks for the catch.

For the log, problem is that end users do not have access to logcat most of the time to provide the logs (And production app should not log to logcat either).

**Comment by ohmae** [comment]
You can replace log output.
```java
Log.setPrint(new Log.Print(){
    @Override
    public void println(final int level, @Nonnull final String tag, @Nonnull final String message) {
        ...
    }
});
```

**Comment by Tolriq** [comment]
I totally missed that, **thanks a lot**, may worth a little addition to readme to help finding that.

**Comment by ohmae** [comment]
There is already a Debug log output section and there is a link to the log library. https://github.com/ohmae/log
