### ISSUE TITLE
java.lang.NoClassDefFoundError on V. 3.0.4

### ISSUE THREAD

**Issue by eakteam** [ohmae/mmupnp#32]
It is crashing after updating from version 3.0.3 -> 3.0.4.
PS : Not because of Proguard/R8 because it is happening in Debug & Release too.

```
2019-07-31 02:05:36.386 8288-8447/com.example E/AndroidRuntime: FATAL EXCEPTION: mmupnp-io-2
    Process: com.example, PID: 8288
    java.lang.NoClassDefFoundError: Failed resolution of: Lnet/mm2d/log/Logger;
        at net.mm2d.upnp.internal.server.SsdpServerDelegate.sendInner(SsdpServerDelegate.kt:108)
        at net.mm2d.upnp.internal.server.SsdpServerDelegate.access$sendInner(SsdpServerDelegate.kt:36)
        at net.mm2d.upnp.internal.server.SsdpServerDelegate$send$1.invoke(SsdpServerDelegate.kt:99)
        at net.mm2d.upnp.internal.server.SsdpServerDelegate$send$1.invoke(SsdpServerDelegate.kt:36)
        at net.mm2d.upnp.internal.thread.TaskExecutors$io$1.run(TaskExecutors.kt:24)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-07-31 02:05:36.386 8288-8446/com.example E/AndroidRuntime: FATAL EXCEPTION: mmupnp-io-1
    Process: com.example, PID: 8288
    java.lang.NoClassDefFoundError: Failed resolution of: Lnet/mm2d/log/Logger;
        at net.mm2d.upnp.internal.server.SsdpServerDelegate.sendInner(SsdpServerDelegate.kt:108)
        at net.mm2d.upnp.internal.server.SsdpServerDelegate.access$sendInner(SsdpServerDelegate.kt:36)
        at net.mm2d.upnp.internal.server.SsdpServerDelegate$send$1.invoke(SsdpServerDelegate.kt:99)
        at net.mm2d.upnp.internal.server.SsdpServerDelegate$send$1.invoke(SsdpServerDelegate.kt:36)
        at net.mm2d.upnp.internal.thread.TaskExecutors$io$1.run(TaskExecutors.kt:24)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by ohmae** [comment]
This is because mmupnp-3.0.4.pom is missing the following description.
```xml
    <dependency>
      <groupId>net.mm2d</groupId>
      <artifactId>log</artifactId>
      <version>0.8.4</version>
      <scope>compile</scope>
    </dependency>
```
I think there is a problem with the build script.
( `:mmupnp:uploadArchives` is no problem but `:mmupnp:bintrayUpload` has problem )
As it takes time to investigate, I have fixed the file of bintray manually, so please try it.
And... If you know well about build scripts, please point out the problem. (Of course I also investigate)

**Comment by eakteam** [comment]
Thanks for answering. Yes it is problem of secondary lib. Keep up the good work
